package scala

class UserException(msg: String) extends RuntimeException(msg)

package object err {

    def internal(message: String): Nothing =
        sys.error(message)

    def usr(message: String): Nothing =
        throw new UserException(message)
}

