try
{
   SomeBigFunction();
}
catch(...)
{
   //Determine exception type here
}

