self.assertRaises(AttributeError, branch[0].childrennodes)
branch[0
childrennodes
AttributeError
assertRaises
AttributeError
Traceback (most recent call last):
  File "/home/tttt/../tttt/tests.py", line 504, in test_get_categories_branch
    self.assertRaises(AttributeError, branch[0].children_nodes)
AttributeError: 'Category' object has no attribute 'children_nodes'

