from Blog.DataObjects.User import say_hello

say_hello()  

Traceback (most recent call last):
  File "index.py", line 1, in <module>
    from Blog.DataObjects import User
ImportError: No module named Blog.DataObjects

